---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
networks:
  kafka-network:
    name: kafka-network

  # Please Read
  # docker-compose -f docker-compose.yml up -d --build   (please run this command to start the kafka server via terminal)

  # docker-compose -f docker-compose.yml down   (please run this command to stop the kafka server via terminal)

  # docker-compose -f docker-compose.yml ps   (please run this command to check the kafka server status via terminal)

  # docker-compose -f docker-compose.yml logs -f   (please run this command to check the kafka server logs via terminal)

  # pease note all following commands are run via seperate  connected terminals except the table_create codes


